apiVersion: v1
kind: Secret
metadata:
  name: xksgo-keys
  namespace: red
data:
  SAT_CLIENT_ID: eDE6eHBjLXFh****mVjOA==
  SAT_CLIENT_SECRET: ZjRiZmY5NjllN****ZWYyMjM3MmI4OGEyYjJkZDc=
  XPC_KEY: QjByM0F1U1dvdE1iWDR****GL2trSHM3VXF0QXZ6dm12clFsdz0=
type: Opaque